name: flutter_archetype
description: A clean architecture Flutter project template ready for production.
publish_to: "none"

version: 1.0.9+2

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  # Core Flutter packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:

flutter:
  uses-material-design: true
