name: hybrid_expansion_tile
description: HybridExpansionTile widget allows creating customized ExpansionTile with various properties like padding, colors, icons, titles, and more.
version: 1.0.1
homepage: https://rudo.es/
repository: https://github.com/rudoapps/hybrid-expansion-tile.git
topics:
  - expansiontile

environment:
  sdk: ">=3.8.6 <4.0.0"

dependencies:
  # Core Flutter packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^7.0.0

dev_dependencies:

flutter:
  uses-material-design: true
